### ISSUE TITLE
Love 10.0?

### ISSUE THREAD

**Issue by HerbFargus** [rm-code/bomb-dodgers#1]
This game is pretty cool. Are there any plans for updating it for Love 10.0?

**Comment by rm-code** [comment]
Thanks :grinning: 

Yeah now that 0.10.0 is officially released I'm going to look into what needs to be updated :ok_hand:

**Comment by rm-code** [comment]
@HerbFargus I think the develop branch should work with 0.10.0 now. 

I couldn't test if the gamepad controls still work since I don't have a gamepad right now.

**Comment by HerbFargus** [comment]
It starts up but then when I try to start a game it says:

```
cannot link shader program object:
ERROR:SEMANTIC-52 (fragment shader , line 23) initializer for uniform
```

then gives a bunch of lines of traceback

**Comment by rm-code** [comment]
Does it give you any other output before that? If so, could you please copy it and post it here? Might be a driver related problem.

**Comment by rm-code** [comment]
Also, were you able to run the game under 0.9.1 (via the binaries)?

**Comment by HerbFargus** [comment]
I'm testing on my raspberry pi and only have 10.0 compiled right now so I'm not sure if 9.1 worked or not. It didn't give any other input but I've attached a photo of the traceback. I tried to turn the shader off to see if it would make a difference but it didn't.
![1454353088451560742919](https://cloud.githubusercontent.com/assets/10035308/12727655/19326d3e-c8db-11e5-805e-80b7f9c0c626.jpg)

**Comment by HerbFargus** [comment]
Renderer is opengl ES version 2.0 
Vendor broadcom
Device videocore IV HW

**Comment by rm-code** [comment]
> Renderer is opengl ES version 2.0 

That explains it! I think OpenGL ES is a bit different from the desktop variant. Should be possible to make the shaders run on a raspi ...

**Comment by rm-code** [comment]
@HerbFargus I've got a Raspberry Pi 3 now. Did you follow any specific guides to compile LÖVE on it? Would love to directly test it on the Pi myself.

**Comment by HerbFargus** [comment]
:D fantastic. Raspberry pi's are the greatest!

Easiest way is to install RetroPie and then install love from the experimental menu of the setup script. 

https://github.com/retropie/retropie-setup/wiki/First-Installation

https://github.com/retropie/retropie-setup/wiki/Love

**Comment by rm-code** [comment]
Thanks!
