### ISSUE TITLE
Shader compatibility with OpenGL ES 2.0

### ISSUE THREAD

**Issue by rm-code** [rm-code/bomb-dodgers#2]
![img](https://cloud.githubusercontent.com/assets/10035308/12727655/19326d3e-c8db-11e5-805e-80b7f9c0c626.jpg)

As discussed in #1 the game currently doesn't run on raspi due to the shaders. Should look into rewriting them.

**Comment by rm-code** [comment]
@HerbFargus Could you please try to run the game with this branch: https://github.com/rm-code/bomb-dodgers/tree/feature/shaders

I changed the shaders. Unfortunately I can't test it myself because I don't own a raspi.

**Comment by HerbFargus** [comment]
Unfortunately it still isn't working

![1454785312127284364327](https://cloud.githubusercontent.com/assets/10035308/12868715/6fc339f2-ccc9-11e5-8035-075ad3a83926.jpg)

**Comment by rm-code** [comment]
@HerbFargus I removed the default initializations of the uniform variables since OpenGL ES doesn't like those. Could you try it again with the latest commit on the shaders branch please? :blush:

**Comment by HerbFargus** [comment]
Unfortunately still not fixed. Just to verify I am doing this correctly: I delete the config file in the love folder just to be sure there aren't any conflicts, I am downloading the zip of the shader branch, recompressing as a .love file and then trying again. - the game loads which means the file is working but when I try to start a game it complains about the shaders. It says line 25 this time so it means that you are making progress ;)

![02072016_022515](https://cloud.githubusercontent.com/assets/10035308/12873588/61409374-cd7e-11e5-86ce-77f9d2cc4bf0.png)

**Comment by HerbFargus** [comment]
I got some help from slime on IRC and found the issue. will submit a pull request.

**Comment by rm-code** [comment]
Fixed via https://github.com/rm-code/bomb-dodgers/commit/af77733ead6653a70abbfd9b9c83126979dff9bb and https://github.com/rm-code/bomb-dodgers/commit/ed77ec3c645554d2d65dd9c89a90322a3f41935f

**Comment by rm-code** [comment]
TODO: Test new splash screen on raspi
